#!/bin/sh
#sh blacklist-generator.sh directory
saveTo=$1
now=$(date);
echo "# Generated by Joshaven Potter on $now" > $saveTo/blacklist.rsc
echo "/ip firewall address-list" >> $saveTo/blacklist.rsc
wget -q -O - http://feeds.dshield.org/block.txt | awk --posix '/^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.0\t/ { print "add list=blacklist address=" $1 "/24 comment=DShield";}' >> $saveTo/blacklist.rsc
wget -q -O - http://www.spamhaus.org/drop/drop.lasso | awk --posix '/[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\// { print "add list=blacklist address=" $1 " comment=SpamHaus";}' >> $saveTo/blacklist.rsc
wget -q -O - http://malc0de.com/bl/IP_Blacklist.txt | awk --posix '/^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/ { print "add list=blacklist address=" $1 " comment=malc0de";}' >> $saveTo/blacklist.rsc
wget -q http://ixp.mikrotik.co.id/download/nice.rsc -O $saveTo/nice.rsc
